name: CD

on:
  workflow_run:
    workflows: ["CI"]     
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only upon successful CI.
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Laravel
      uses: docker/build-push-action@v5
      with:
        context: ./laravel
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-foods-laravel:latest
        
    - name: Build and push Symfony
      uses: docker/build-push-action@v5
      with:
        context: ./symfony
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-foods-symfony:latest
        
    - name: Deploy to production
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /opt/mongo-foods
          docker-compose pull
          docker-compose up -d
          docker system prune -f 