name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test Laravel
      run: |
        docker-compose build laravel
        docker-compose up -d mongodb laravel
        docker-compose exec -T laravel composer install
        docker-compose exec -T laravel php artisan test
        
    # - name: Build and test Symfony
    #   run: |
    #     docker-compose build symfony
    #     docker-compose up -d symfony
    #     docker-compose exec -T symfony composer install
    #     docker-compose exec -T symfony php bin/phpunit
        
    - name: Cleanup
      if: always()
      run: docker-compose down 