name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Поднимаем Docker-in-Docker как сервис
    services:
      docker:
        image: docker:24.0.2-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          # Отключаем TLS в самом демоне
          DOCKER_TLS_CERTDIR: ""

    # Указываем клиенту, куда стучаться
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Docker daemon
        run: |
          for i in $(seq 1 15); do
            if docker info >/dev/null 2>&1; then
              echo "Docker daemon is up"; break
            fi
            echo "Waiting for Docker…"; sleep 1
          done

      - name: Build and test Laravel
        run: |
          # Новым плагином docker compose
          docker compose build laravel
          docker compose up -d mongodb laravel
          docker compose exec -T laravel composer install --ansi --no-interaction
          docker compose exec -T laravel php artisan test --parallel

      - name: Cleanup
        if: always()
        run: docker compose down --volumes --remove-orphans
